pa/contacts/urls.py
from django.urls import path

from . import views

app_name = "contacts"

urlpatterns = [
    path("contacts/", views.contacts, name="contacts"),
    path("contact/<int:id>/", views.contact, name="contact"),
    path("contact/<int:id>/delete/", views.delete_contact, name="delete_contact"),
    path("contact/<int:id>/edit", views.edit_contact, name="edit_contact"),
    path("contacts/create/", views.create_contact, name="create_contact"),
    path("contacts/search/", views.find_contact, name="find_contact"),
    path("contacts/upcoming_birthdays/", views.upcoming_birthdays, name="upcoming_birthdays"),
]

pa/news/urls.py
from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path("", views.main, name="main"),
    path("quotes/", views.main, name="main"),
    path("quotes/get", views.quotes_get, name="quotes_get"),
    path("economics/", views.economics, name="economics"),
    path("economics/get", views.economics_get, name="economics_get"),
    path("politics/", views.politics, name="politics"),
    path("politics/get", views.politics_get, name="politics_get"),
    path("weather/", views.weather, name="weather"),
    path("weather/get", views.weather_get, name="weather_get"),
]

pa/notes/urls.py
from django.urls import path

from . import views

app_name = "notes"

urlpatterns = [
    path("all-notes/", views.all_notes, name="all_notes"),
    path("add-note/", views.add_note, name="add_note"),
    path("note/<int:id>/", views.note, name="note"),
    path("note/<int:id>/edit/", views.edit_note, name="edit_note"),
    path("note/<int:id>/delete/", views.delete_note, name="delete_note"),
    path("find-notes/", views.find_notes, name="find_notes"),
    path("by-name/", views.by_name, name="by_name"),
    path("by-tag/", views.by_tag, name="by_tag"),
    path("all-notes/tag/<str:name>", views.by_tag_name, name="by_tag_name")
]

pa/pa/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views

from .api import NewsQuoteResource

news_quote_resource = NewsQuoteResource()

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.main_page, name="main_page"),
    path("", include("notes.urls")),
    path("", include("contacts.urls")),
    path("users/", include("users.urls")),
    path("news/", include("news.urls")),
    path("storage/", include("storage.urls")),
    path("random_quote_api/", views.random_quote_api, name="random_quote_api"),
    path("road_map/", views.road_map, name="road_map"),

    path("reviews/", views.reviews, name="reviews"),

    re_path(r"^api/", include(news_quote_resource.urls)),
]

pa/urls.py
from django.conf.urls import handler404
from pa.views.error_views import handler404  # импортируйте ваш обработчик

handler404 = 'pa.views.error_views.handler404'

pa/users/urls.py
from django.contrib.auth.views import (PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView)
from django.urls import path

from . import views
from .views import (ActivateAccountView, ActivationSuccessView,
                    EmailVerificationSentView, RegisterView)

app_name = "users"

urlpatterns = [
    # path("", views.users_main, name="users_main"),
    path("register/", RegisterView.as_view(), name="register"),
    path("activate/<uidb64>/<token>/", ActivateAccountView.as_view(), name="activate"),
    path(
        "email-verification-sent/",
        EmailVerificationSentView.as_view(),
        name="email_verification_sent",
    ),
    path(
        "activation-success/",
        ActivationSuccessView.as_view(),
        name="activation_success",
    ),
    path("login/", views.login_view, name="login"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logout_view, name="logout"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

pa/templates/_auth_menu.html
<li><a href="{% url 'news:main' %}">News</a></li>
<li><a href="{% url 'contacts:contacts' %}">Contacts</a></li>
<li><a href="{% url 'notes:all_notes' %}">Notes</a></li>
<li><a href="{% url 'storage:file_list' %}">File storage</a></li>
<li><a href="{% url 'users:profile' %}">Profile</a></li>
<li><a href="{% url 'users:logout' %}">Logout</a></li>

pa/templates/_main.html
{% load static %}
<section class="_content_block_1">
  <div class="wr">
    <header class="_6dbf6d99">
      <h2 class="_06745472">Key Benefits</h2>
      <p class="_0954f0bf">
        Experience the essence of efficiency with PersonalAssistanse&#x27;s key
        features - an ode to minimalism in a world of digital noise.
      </p>
    </header>
    <div class="_b74af010">
      <div class="_d7c3134c">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="um-icon _aa3545e6"
          fill="currentColor"
          width="24"
          height="24"
          viewBox="0 0 24 24">
          <path
            d="M13.5.67s.74 2.65.74 4.8c0 2.06-1.35 3.73-3.41 3.73-2.07 0-3.63-1.67-3.63-3.73l.03-.36C5.21 7.51 4 10.62 4 14c0 4.42 3.58 8 8 8s8-3.58 8-8C20 8.61 17.41 3.8 13.5.67zM11.71 19c-1.78 0-3.22-1.4-3.22-3.14 0-1.62 1.05-2.76 2.81-3.12 1.77-.36 3.6-1.21 4.62-2.58.39 1.29.59 2.65.59 4.04 0 2.65-2.15 4.8-4.8 4.8z"
          ></path>
        </svg>
        <h3 class="_40c675ce">Cloud Sync</h3>
        <span class="_5da1b81b"
          >Keep your documents, contacts, and notes in sync across all
          your devices with our secure cloud storage solution.</span
        >
      </div>
      <div class="_d7c3134c">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="um-icon _aa3545e6"
          fill="currentColor"
          width="24"
          height="24"
          viewBox="0 0 24 24">
          <path
            d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10 10-4.5 10-10S17.5 2 12 2zm4.2 14.2L11 13V7h1.5v5.2l4.5 2.7-.8 1.3z"
          ></path>
        </svg>
        <h3 class="_40c675ce">Daily Digest</h3>
        <span class="_5da1b81b"
          >Stay informed with a curated list of news? inspirational
          quotes and weather delivered to your personalized feed every morning.</span
        >
      </div>
      <div class="_d7c3134c">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="um-icon _aa3545e6"
          fill="currentColor"
          width="24"
          height="24"
          viewBox="0 0 24 24">
          <path
            d="M19.36 10.04C18.67 6.59 15.64 4 12 4 9.11 4 6.6 5.64 5.35 8.04A5.994 5.994 0 0 0 0 14c0 3.31 2.69 6 6 6h13c2.76 0 5-2.24 5-5 0-2.64-2.05-4.78-4.64-4.96z"
          ></path>
        </svg>
        <h3 class="_40c675ce">Quick Access</h3>
        <span class="_5da1b81b"
          >Retrieve any file or contact detail with lightning-fast search
          and quick-access widgets designed for efficiency.
        </span>
      </div>
      <div class="_d7c3134c">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="um-icon _aa3545e6"
          fill="currentColor"
          width="24"
          height="24"
          viewBox="0 0 24 24">
        <path 
        d="M12 22c1.1 0 2-.9 2-2h-4a2 2 0 0 0 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"
        ></path>
        </svg>
        <h3 class="_40c675ce">Reminders</h3>
        <span class="_5da1b81b"
          >Receive reminders whenever your contacts' birthday approaches.
        </span>
      </div>
    </div>
  </div>
</section>
<section class="_1923fe83">
  <div class="wr">
    <div class="_15cacd0c">
      <div class="_content_left_block">
        <header class="_af4fe10b">
          <h2 class="_060ab2a4">FAQs</h2>
          <p class="_defae18f">
            Have questions? We&#x27;ve compiled a list of frequently asked
            questions to help you better understand PersonalAssistanse and its
            benefits.
          </p>
        </header>
      </div>
      <div class="_content_right_block">
        <div class="_3f613442">
          <h4 class="_8239ae20">How secure is PersonalAssistanse?</h4>
          <div class="_1b1643a8">
            With state-of-the-art encryption and privacy controls, your data
            is always safe with PersonalAssistanse. Experience true digital security.
          </div>
        </div>
        <div class="_3f613442">
          <h4 class="_8239ae20">Can I customize my newsfeed?</h4>
          <div class="_1b1643a8">
            Absolutely! Our newsfeed is fully customizable, allowing you to
            select topics and sources that matter most to you.
          </div>
        </div>
        <div class="_3f613442">
          <h4 class="_8239ae20">What file types are supported?</h4>
          <div class="_1b1643a8">
            PersonalAssistanse supports a wide variety of file types, offering you
            flexibility in how you store and manage your documents.
          </div>
        </div>
        <div class="_3f613442">
          <h4 class="_8239ae20">Is there a mobile version?</h4>
          <div class="_1b1643a8">
            PersonalAssisante is available now on both your smartphone and tablet, 
            giving you seamless access to your data wherever you are. All you need is 
            Internet access and a browser. We are planning to make a separate application 
            in the very near future
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="_1923fe83">
  <div class="wr">
    <header class="_1923fe83">
      <h2 class="_06745472">The project team</h2>
      <p class="_0954f0bf">
        This project was created in two weeks by a team of novice developers as a result of the course PythonWEB in GoIT
      </p>
    </header>
    <div class="_b74af010">
      <div class="_d7c3134c">
        <img src="{% static '_anton.jpg' %}"
          class="team_photo">
        <h3 class="_40c675ce">Anton Tarasov</h3>
        <span class="_5da1b81b">Storage, Upload, HTML, CSS, install on Ubuntu/Linux</span>
      </div>
      <div class="_d7c3134c">
          <img src="{% static '_oleg.jpg' %}"
            class="team_photo">
        <h3 class="_40c675ce">Oleh Davydenko</h3>
        <span class="_5da1b81b">News, RestAPI, HTML, CSS, install on Windows</span>
      </div>
      <div class="_d7c3134c">
          <img src="{% static '_polina.jpg' %}"
            class="team_photo">
        <h3 class="_40c675ce">Polina Mamchur</h3>
        <span class="_5da1b81b">Reminder, send email, testing</span>
      </div>
      <div class="_d7c3134c">
          <img src="{% static '_stepan.png' %}"
            class="team_photo">
        <h3 class="_40c675ce">Stepan Udod</h3>
        <span class="_5da1b81b">Contacts, Notes, HTML, CSS, </span>
      </div>
    </div>
  </div>
</section>

pa/templates/_not_auth_menu.html
<a href="{% url 'users:login' %}" class="_ad787885 btn">
    <span>Sign In</span></a>
<a href="{% url 'users:register' %}" class="_0c5b1f56 btn">
    <span>Get Started</span></a>

pa/templates/_reviews.html
{% load static %}
<section class="_content_block_1">
  <div class="wr">
    <header class="_1923fe83">
      <h2 class="_06745472">Reviews</h2>
      <p class="_0954f0bf">
        Our team convened a small focus group to gather requirements for this application and conducted in-depth interviews with each focus group member. We showed them the minimally useful version and got feedback.
      </p>
    </header>
    <div class="_b74af010">
      <div class="_d7c3134c">
        <img src="{% static '_sarah.jpeg' %}"
          class="team_photo">
        <h3 class="_40c675ce">Sarah Williams</h3>
        <span class="_5da1b81b">Primary school teacher, 34 years old</span>
      
        <span class="_5da1b81b">"This program has changed my approach to organizing my work process! It is incredibly convenient and easy to use. Now I have all the information at my fingertips, and I can easily keep my educational materials in order. I recommend it to all teachers!"</span>
      </div>
      <div class="_d7c3134c">
          <img src="{% static '_michael.jpeg' %}"
            class="team_photo">
        <h3 class="_40c675ce">Michael Johnson</h3>
        <span class="_5da1b81b">Freelancer, graphic designer, 29 years old</span>
        <span class="_5da1b81b">"I've always been looking for a tool to help me organize my files. This product does just that! Now all my projects and files are organized in one place. The simplicity of the interface is amazing and I'm sure I won't lose a single important file."</span>
      </div>
      <div class="_d7c3134c">
          <img src="{% static '_emily.jpeg' %}"
            class="team_photo">
        <h3 class="_40c675ce">Emily Black</h3>
        <span class="_5da1b81b">Marketing Manager, 42 years old</span>
        <span class="_5da1b81b">"With this program, my workspace has become much more organized. All information is now in one place, which allows me to quickly find the files and documents I need. Convenience and ease of use make this product an indispensable tool for any professional."</span>
      </div>
      <div class="_d7c3134c">
          <img src="{% static '_david.jpeg' %}"
            class="team_photo">
        <h3 class="_40c675ce">David Brown</h3>
        <span class="_5da1b81b">IT specialist, 37 years old</span>
        <span class="_5da1b81b">“This software is a real godsend! It is so convenient and easy to use that I instantly put all my documents in order. Now I always have all the necessary information at hand, and keeping order has become a breeze. Simply amazing!”</span>
      </div>
    </div>
  </div>
</section>

pa/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <meta name="viewport"
              content="width=device-width,initial-scale=1,shrink-to-fit=no" />
        <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />
        <link rel="stylesheet" href="{% static 'style.css' %}" />
        <link rel="stylesheet" href="{% static 'style_news.css' %}" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
              rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
        <title>
            {% block title %}Personal Assistance Site{% endblock %}
        </title>
        <link href="https://fonts.googleapis.com/css2?family=Cardo:wght@700&amp;family=Lato:wght@400;700&amp;display=block"
              rel="stylesheet" />
    </head>
    <body>
        <section class="menu_section">
            <div class="wr">
                <div class="_f4c879d8">
                    <div class="_9698a7cf" style="--gap: 1; font-size: 16px">
                        <a href="{% url 'main_page' %}">
                            <div class="_f7a17dd3" style="--scale: 1">
                                <img src="{% static '_pa_logo.png' %}" />
                            </div>
                            <span class="_3c86000f">PersonalAssistance</span>
                        </a>
                    </div>
                    <nav id="kmw87btk3o" class="_2306d92f um-nav-wrapper um-classic um-hidden">
                        <div class="um-nav-children"></div>
                        {% if user.is_authenticated %}
                            <ul class="um-nav-links">
                                {% include '_auth_menu.html' %}
                            </ul>
                        {% endif %}
                        {% if not user.is_authenticated %}
                            <div class="um-nav-buttons">{% include '_not_auth_menu.html' %}</div>
                        {% endif %}
                    </nav>
                    <button id="kmw87btk3o-drawerTrigger"
                            class="um-nav-drawerTrigger"
                            title="Open Mobile Menu"></button>
                    <div id="kmw87btk3o-drawer" class="_2306d92f um-nav-drawer um-hidden">
                        <header>
                            <button class="um-nav-drawerClose">
                                <svg xmlns="http://www.w3.org/2000/svg"
                                     width="24"
                                     height="24"
                                     viewBox="0 0 24 24"
                                     fill="none"
                                     stroke="currentColor"
                                     stroke-width="2"
                                     stroke-linecap="round"
                                     stroke-linejoin="round">
                                    <line x1="18" y1="6" x2="6" y2="18"></line>
                                    <line x1="6" y1="6" x2="18" y2="18"></line>
                                </svg>
                            </button>
                        </header>
                        {% if user.is_authenticated %}
                            <div class="um-drawer-links">{% include '_auth_menu.html' %}</div>
                        {% endif %}
                        {% if not user.is_authenticated %}
                            <div class="um-drawer-buttons">{% include '_not_auth_menu.html' %}</div>
                        {% endif %}
                    </div>
                    <script>
            !(function () {
              const e = document.getElementById("kmw87btk3o");
              if (!e) return;
              const t = document.getElementById("kmw87btk3o-drawerTrigger"),
                n = document.getElementById("kmw87btk3o-drawer");
              document.addEventListener("click", function (e) {
                n.contains(e.target) ||
                  e.target === t ||
                  n.classList.add("um-hidden");
              });
              const d = n.querySelector(".um-nav-drawerClose"),
                s = n.querySelectorAll(".um-drawer-links > li > button"),
                i = e.querySelector(".um-nav-children"),
                r = e.querySelector(".um-nav-links"),
                c = e.querySelector(".um-nav-buttons");
              t.addEventListener("click", function () {
                n.classList.remove("um-hidden");
              }),
                d.addEventListener("click", function () {
                  n.classList.add("um-hidden");
                }),
                s.forEach(function (e) {
                  e.addEventListener("click", function () {
                    this.parentNode.classList.toggle("um-open");
                  });
                });
              let o = 0,
                u = !0;
              function a() {
                !1 === u &&
                  (o =
                    (i?.offsetWidth || 0) +
                    (r?.offsetWidth || 0) +
                    (c?.offsetWidth || 0)),
                  l();
              }
              function l() {
                e.offsetWidth - 10 < o
                  ? ((u = !0),
                    e.classList.add("um-hidden"),
                    t.classList.remove("um-hidden"))
                  : ((u = !1),
                    e.classList.remove("um-hidden"),
                    t.classList.add("um-hidden"),
                    n.classList.add("um-hidden"));
              }
              new ResizeObserver(l).observe(document.body),
                i && new ResizeObserver(a).observe(i),
                c && new ResizeObserver(a).observe(c),
                r && new ResizeObserver(a).observe(r),
                a(),
                l();
            })();
                    </script>
                </div>
            </div>
        </section>
        {% block content %}
        {% endblock %}
        <footer class="_c4b89fde">
            <div class="wr">
                <div class="_bea1daea">
                    <div class="_240f2910">
                        <span class="_c0e4633f">© 2024 PersonalAssistance</span>
                    </div>
                    <ul class="_d1a0a8ea">
                        <li class="_0fc50e27">
                            <h4 class="_31f6b92b">Features</h4>
                            <ul class="_91687afc">
                                <li class="_e0485177">
                                    <a href="{% url 'random_quote_api' %}">Random Quote API</a>
                                </li>
                                <li class="_e0485177">
                                    <a href="https://github.com/avtarso/personal_assistance"
                                       class="_c288f4a7">GitHub Repository</a>
                                </li>
                                <li class="_e0485177">
                                    <a href="{% url 'road_map' %}">Road map</a>
                                </li>
                                <li class="_e0485177">
                                    <a href="{% url 'reviews' %}">Reviews</a>
                                </li>
                            </ul>
                        </li>
                        <li class="_0fc50e27">
                            <h4 class="_31f6b92b">Our team</h4>
                            <ul class="_91687afc">
                                <li class="_e0485177">
                                    <a href="https://github.com/avtarso" class="_c288f4a7">Anton Tarasov</a>
                                </li>
                                <li class="_e0485177">
                                    <a href="https://github.com/davydenkoo" class="_c288f4a7">Oleh Davydenko</a>
                                </li>
                                <li class="_e0485177">
                                    <a href="https://github.com/polinamamchur" class="_c288f4a7">Polina Mamchur</a>
                                </li>
                                <li class="_e0485177">
                                    <a href="https://github.com/sheitanbratan" class="_c288f4a7">Stepan Udod</a>
                                </li>
                            </ul>
                        </li>
                        <li class="_0fc50e27">
                            <h4 class="_31f6b92b">Legal</h4>
                            <ul class="_91687afc">
                                <li class="_e0485177">
                                    <a href="/privacy-policy" class="_c288f4a7">Privacy Policy</a>
                                </li>
                                <li class="_e0485177">
                                    <a href="/terms-of-use" class="_c288f4a7">Terms of Use</a>
                                </li>
                                <li class="_e0485177">
                                    <a href="/cookie-policy" class="_c288f4a7">Cookie Policy</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </footer>
    </body>
</html>

pa/templates/index.html
{% extends 'base.html' %}

{% block title %}Personal Assistance Site{% endblock %}

{% block content %}

{% include '_main.html' %}

{% endblock %}

pa/templates/random_quote_api.html
{% extends 'base.html' %}

{% block title %}Contacts{% endblock %}

{% block content%}

<section class="_content_block_1">
    <div class="wr">
      <div class="_15cacd0c">
        <div class="_content_left_block">
          <header class="_af4fe10b">
            <h2 class="_060ab2a4">Features</h2>
            Random Quote API
          </header>
        </div>
        <div class="_content_right_block">
          <div class="_3f613442">
            <h4 class="_8239ae20">Random Quote API</h4>
            <br />
            <div class="_1b1643a8">
              <p>A registered user can receive a random quote by sending the following request:</p>
              <pre>
curl -u "username:password" -H "Accept: application/json" 
https://personalassistance-production.up.railway.app/api/news_quote/
              </pre>
              <p>values "username:password" ​​must be replaced with real ones</p>

              <br /><a href="/api/news_quote/?format=json" class="_c288f4a7">Example for registred user</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  {% endblock %}

pa/templates/reviews.html
{% extends 'base.html' %}

{% block title %}Personal Assistance Site{% endblock %}

{% block content %}

{% include '_reviews.html' %}

{% endblock %}

pa/templates/road_map.html
{% extends 'base.html' %}

{% block title %}Personal Assistance Site{% endblock %}

{% block content %}

<section class="_content_block_1">
    <div class="wr">
      <div class="_15cacd0c">
        <div class="_content_left_block">
          <header class="_af4fe10b">
            <h2 class="_060ab2a4">Road map</h2>
          </header>
        </div>
        <div class="_content_right_block">
          <div class="_3f613442">
            <h4 class="_8239ae20">What are we planning to do next?</h4>
            <div class="_1b1643a8">
              <br />
                <ul>
                    <li>Creating an application<br />
                        - Ability to synchronize your contact list via the mobile application<br />
                        - sending reminders through the application</li>

                    <li>Creating a telegram bot<br />
                        - registration via telegram<br />
                        - ability to save sent files to the bot<br />
                        - sending reminders via bot<br />
                        - synchronization with telegram contacts</li>

                    <li>Sending reminders about file review deadlines</li>

                    <li>Synchronizing data with Google Sheets</li>

                    <li>Ability to synchronize your contact list via a mobile application</li>

                    <li>Ability to download/upload information in csv format</li>

                    <li>Create an analogue of Google reader</li>

                </ul>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}