pa/notes/urls.py
from django.urls import path

from . import views

app_name = "notes"

urlpatterns = [
    path("all-notes/", views.all_notes, name="all_notes"),
    path("add-note/", views.add_note, name="add_note"),
    path("note/<int:id>/", views.note, name="note"),
    path("note/<int:id>/edit/", views.edit_note, name="edit_note"),
    path("note/<int:id>/delete/", views.delete_note, name="delete_note"),
    path("find-notes/", views.find_notes, name="find_notes"),
    path("by-name/", views.by_name, name="by_name"),
    path("by-tag/", views.by_tag, name="by_tag"),
    path("all-notes/tag/<str:name>", views.by_tag_name, name="by_tag_name")
]

pa/pa/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views

from .api import NewsQuoteResource

news_quote_resource = NewsQuoteResource()

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.main_page, name="main_page"),
    path("", include("notes.urls")),
    path("", include("contacts.urls")),
    path("users/", include("users.urls")),
    path("news/", include("news.urls")),
    path("storage/", include("storage.urls")),
    path("random_quote_api/", views.random_quote_api, name="random_quote_api"),
    path("road_map/", views.road_map, name="road_map"),

    path("reviews/", views.reviews, name="reviews"),

    re_path(r"^api/", include(news_quote_resource.urls)),
]

pa/urls.py
from django.conf.urls import handler404
from pa.views.error_views import handler404  # импортируйте ваш обработчик

handler404 = 'pa.views.error_views.handler404'

pa/notes/models.py
from django.contrib.auth.models import User
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Note(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(blank=True, null=True)
    tags = models.ManyToManyField(Tag)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.name}: {self.description}, {self.tags}"

pa/notes/forms.py
from django import forms

from .models import Note, Tag


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["name"]


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ["name", "description", "tags"]
        labels = {
            "name": "Note`s short name",
            "description": "Note`s description",
            "tags": "Tags"
        }

pa/notes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from .models import Note, Tag


def paginator(request, data):
    paginator = Paginator(data, 5)  # Number elements on page
    page = request.GET.get('page', 1)
    try:
        data_paginated = paginator.page(page)
    except PageNotAnInteger:
        data_paginated = paginator.page(1)
    except EmptyPage:
        data_paginated = paginator.page(paginator.num_pages)
    return data_paginated


@login_required
def note(request, id):
    note = get_object_or_404(Note, id=id, added_by=request.user)
    return render(request, "notes/note.html", {"note": note})


@login_required
def all_notes(request):
    notes = Note.objects.filter(added_by=request.user).order_by("-id")
    return render(
        request,
        "notes/all_notes.html",
        {
            "notes": paginator(request, notes)
        }
    )


@login_required
def add_note(request):
    if request.method == "POST":

        raw_tags = request.POST.get('tags')
        tags = []
        for t in raw_tags.split(','):
            tag, _ = Tag.objects.get_or_create(name=t.strip())
            tags.append(tag)

        user = request.user
        note_name = request.POST.get('name')
        description = request.POST.get('description')
        note = Note.objects.create(
            name=note_name,
            description=description,
            added_by=user
        )
        note.tags.set(tags)

        return redirect('notes:all_notes')

    return render(request, "notes/add_note.html")


@login_required
def edit_note(request, id):
    note = get_object_or_404(Note, id=id, added_by=request.user)
    if request.method == "POST":
        note.name = request.POST["new_name"]
        note.description = request.POST["new_description"]

        raw_tags = request.POST["new_tags"]
        tags = []
        for t in raw_tags.split(','):
            if len(t) != 0:
                tag, _ = Tag.objects.get_or_create(name=t.strip())
                tags.append(tag)

        note.tags.set(tags)
        note.save()

        return redirect('notes:all_notes')
    return render(request, 'notes/edit_note.html', {'note': note})


@login_required
def delete_note(request, id):
    note = get_object_or_404(Note, id=id, added_by=request.user)
    if request.method == "POST":
        note.delete()
        return redirect('notes:all_notes')
    return render(request, "notes/delete_note.html", {"note": note})


@login_required
def find_notes(request):
    return render(request, "notes/find_notes.html")


@login_required
def by_name(request):
    result = []
    if request.method == "POST":
        name = request.POST.get("name", "")
        result = Note.objects.filter(name__icontains=name, added_by=request.user)
    return render(
        request,
        "notes/search_result.html",
        {
            "notes": paginator(request, result)
        }
    )


@login_required
def by_tag(request):
    result = []
    if request.method == "POST":
        tag = request.POST.get("tag", "")
        result = Note.objects.filter(tags__name__icontains=tag, added_by=request.user)
    return render(
        request,
        "notes/search_result.html",
        {
            "notes": paginator(request, result)
        }
    )


@login_required
def by_tag_name(request, name):
    tag = get_object_or_404(Tag, name=name)
    result = Note.objects.filter(tags__name__icontains=tag, added_by=request.user)
    return render(
        request,
        "notes/search_result.html",
        {
            "notes": paginator(request, result)
        }
    )

pa/notes/templates/notes/_note_detail.html
    <strong>{{ note.name }}</stronf>
    <ul>
        {% if note.description %}
        <li>Description: {{ note.description }}</li>
        {% endif %}
        {% if note.tags %}
        <li>Tags: {% for tag in note.tags.values %} <a href="/all-notes/tag/{{ tag.name }}">#{{ tag.name }}</a> {% endfor %}</li>
        {% endif %}
    </ul>
    <a href="edit">Edit</a> - <a href="delete">Delete</a>

pa/notes/templates/notes/_notes_menu.html
<ul>
    <li><a href="{% url 'notes:add_note' %}">New Note</a></li>

</ul>

pa/notes/templates/notes/_pagination.html
<div class="pagination">
    <span class="step-links">
        {% if notes.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ notess.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">
            Page {{ notes.number }} of {{ notes.paginator.num_pages }}.
        </span>

        {% if notes.has_next %}
            <a href="?page={{ notes.next_page_number }}">next</a>
            <a href="?page={{ notes.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

pa/notes/templates/notes/_search_form.html
<ul class="by_name">
    <form class="search-form" action="{% url 'notes:by_name' %}" method="post">
        {% csrf_token %}
        <input class="form-control"
               type="text"
               id="id_name"
               name="name"
               placeholder="Search by note`s title">
        <input type="submit"
               value="Search"
               class="btn btn-light btn-sm border border-1 ms-1">
    </form>
</ul>
<ul class="by_tag">
    <form class="search-form" action="{% url 'notes:by_tag' %}" method="post">
        {% csrf_token %}
        <input class="form-control"
               type="text"
               id="id_tag"
               name="tag"
               placeholder="Search by note`s tag">
        <input type="submit"
               value="Search"
               class="btn btn-light btn-sm border border-1 ms-1">
    </form>
</ul>

pa/notes/templates/notes/add_note.html
{% extends "base.html" %}

{% block title %}Add note{% endblock %}

{% block content %}

<section class="_content_block_1">
    <div class="wr">
        <div class="_15cacd0c">
            <div class="_content_left_block">
                <header class="_af4fe10b">
                    <h2 class="_060ab2a4">Notes</h2>
                    {% include 'notes/_notes_menu.html' %}
                    {% include 'notes/_search_form.html' %}
                </header>
            </div>
            <div class="_content_right_block">
                <div class="_3f613442">
                    <h4 class="_8239ae20">Add new note</h4>
                    <br />
                    <div class="_1b1643a8">
                        <form action="{% url 'notes:add_note' %}" method="post">
                            {% csrf_token %}
                            <div>
                                <label for="id_name">Title:</label>
                                <input type="text" class="form-control" id="id_name" name="name">
                            </div>
                            <div>
                                <label for="id_description">Description:</label>
                                <input type="text" class="form-control" id="id_description" name="description">
                            </div>
                            <div>
                                <label for="id_tags">Tags:</label>
                                <input type="text" class="form-control" id="id_tags" name="tags">
                            </div>
                            <input type="submit" value="Add" class="btn btn-primary">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

pa/notes/templates/notes/all_notes.html
{% extends 'base.html' %}

{% block title %}All notes{% endblock %}

{% block content%}

<section class="_content_block_1">
    <div class="wr">
        <div class="_15cacd0c">
            <div class="_content_left_block">
                <header class="_af4fe10b">
                    <h2 class="_060ab2a4">Notes</h2>
                    {% include 'notes/_notes_menu.html' %}
                    {% include 'notes/_search_form.html' %}
                </header>
            </div>
            <div class="_content_right_block">
                <div class="_3f613442">
                    <h4 class="_8239ae20">Notes</h4>
                    <br />
                    <div class="_1b1643a8">
                        <ul>
                            {% for note in notes %}
                                <li>
                                    <strong>{{note.name}}</strong>
                                    <ul>
                                        {% if note.description %}
                                            <li>Description: {{ note.description }}</li>
                                        {% endif %}
                                        {% if note.tags %}
                                            <li>Tags: {% for tag in note.tags.values %} <a href="/all-notes/tag/{{ tag.name }}">#{{ tag.name }}</a> {% endfor %}</li>
                                        {% endif %}
                                    </ul>
                                    <a href="/note/{{note.id}}/edit">Edit</a>
                                    <a href="/note/{{note.id}}/delete">Delete</a>
                                </li>
                                <br /><br />
                            {% endfor %}
                        </ul>
                        {% include 'notes/_pagination.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

pa/notes/templates/notes/delete_note.html
{% extends 'base.html' %}

{% block title %}Delete Note{% endblock %}

{% block content%}

<section class="_content_block_1">
    <div class="wr">
        <div class="_15cacd0c">
            <div class="_content_left_block">
                <header class="_af4fe10b">
                    <h2 class="_060ab2a4">Notes</h2>
                    {% include 'notes/_notes_menu.html' %}
                    {% include 'notes/_search_form.html' %}
                </header>
            </div>
            <div class="_content_right_block">
                <div class="_3f613442">
                    <h4 class="_8239ae20">Delete Note "{{ note.name }}"</h4>
                    <br />
                    <div class="_1b1643a8">
                        <strong>Are you sure you want to delete the note "{{ note.name }}"?</strong>
                        <form method="post">
                            {% csrf_token %}
                            <button type="submit">Yes, delete</button>
                            <a href="{% url 'notes:all_notes' %}">Cancel</a>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

pa/notes/templates/notes/edit_note.html
{% extends "base.html" %}

{% block title %}Edit note - "{{ note.name }}"{% endblock %}

{% block content %}

<section class="_content_block_1">
    <div class="wr">
        <div class="_15cacd0c">
            <div class="_content_left_block">
                <header class="_af4fe10b">
                    <h2 class="_060ab2a4">Notes</h2>
                    {% include 'notes/_notes_menu.html' %}
                    {% include 'notes/_search_form.html' %}
                </header>
            </div>
            <div class="_content_right_block">
                <div class="_3f613442">
                    <h4 class="_8239ae20">Enter new information for {{ note.name }}</h4>
                    <br />
                    <div class="_1b1643a8">
                        <form method="post">
                            {% csrf_token %}
                            <div class="row" bis_skin_checked="1">
                                <div class="form-group col-xs-3" bis_skin_checked="1">
                                    <label for="id_new_name">Title:</label>
                                    <input type="text" class="form-control" id="id_new_name" name="new_name" value="{{ note.name }}">
                                </div>
                            </div>
                            <div class="row" bis_skin_checked="1">
                                <div class="form-group col-xs-3" bis_skin_checked="1">
                                    <label for="id_new_description">Description:</label>
                                    <input type="text" class="form-control" id="id_new_description" name="new_description" value="{{ note.description }}">
                                </div>
                            </div>
                            <div class="row" bis_skin_checked="1">
                                <div class="form-group col-xs-3" bis_skin_checked="1">
                                    <label for="id_new_tags">Tags:</label>
                                    <input type="text" class="form-control" id="id_new_tags" name="new_tags" value="{% for tag in note.tags.values %} {{ tag.name }},{% endfor %}">
                                </div>
                            </div>
                            <input type="submit" value="Confirm" class="btn btn-primary">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

pa/notes/templates/notes/note.html
{% extends "base.html" %}

{% block title %}Details of Note "{{ note.name }}"{% endblock %}

{% block content %}

<section class="_content_block_1">
    <div class="wr">
        <div class="_15cacd0c">
            <div class="_content_left_block">
                <header class="_af4fe10b">
                    <h2 class="_060ab2a4">Notes</h2>
                    {% include 'notes/_notes_menu.html' %}
                    {% include 'notes/_search_form.html' %}
                </header>
            </div>
            <div class="_content_right_block">
                <div class="_3f613442">
                    <h4 class="_8239ae20">Details of Note "{{ note.name }}"</h4>
                    <br />
                    <div class="_1b1643a8">
                        {% include 'notes/_note_detail.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

pa/notes/templates/notes/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if notes.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ files.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">
            Page {{ notes.number }} of {{ notes.paginator.num_pages }}.
        </span>

        {% if notes.has_next %}
            <a href="?page={{ files.next_page_number }}">next</a>
            <a href="?page={{ files.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

pa/notes/templates/notes/search_result.html
{% extends 'base.html' %}

{% block title %}Results search in Notes{% endblock %}

{% block content%}

<section class="_content_block_1">
    <div class="wr">
        <div class="_15cacd0c">
            <div class="_content_left_block">
                <header class="_af4fe10b">
                    <h2 class="_060ab2a4">Notes</h2>
                    {% include 'notes/_notes_menu.html' %}
                    {% include 'notes/_search_form.html' %}
                </header>
            </div>
            <div class="_content_right_block">
                <div class="_3f613442">
                    <h4 class="_8239ae20">Notes</h4>
                    <br />
                    <div class="_1b1643a8">
                        <ul>
                            {% for note in notes %}
                            <li>{% include 'notes/_note_detail.html' %}</li>
                            {% endfor %}
                        </ul>
                        {% include 'notes/_pagination.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}