pa/contacts/urls.py
from django.urls import path

from . import views

app_name = "contacts"

urlpatterns = [
    path("contacts/", views.contacts, name="contacts"),
    path("contact/<int:id>/", views.contact, name="contact"),
    path("contact/<int:id>/delete/", views.delete_contact, name="delete_contact"),
    path("contact/<int:id>/edit", views.edit_contact, name="edit_contact"),
    path("contacts/create/", views.create_contact, name="create_contact"),
    path("contacts/search/", views.find_contact, name="find_contact"),
    path("contacts/upcoming_birthdays/", views.upcoming_birthdays, name="upcoming_birthdays"),
]

pa/news/urls.py
from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path("", views.main, name="main"),
    path("quotes/", views.main, name="main"),
    path("quotes/get", views.quotes_get, name="quotes_get"),
    path("economics/", views.economics, name="economics"),
    path("economics/get", views.economics_get, name="economics_get"),
    path("politics/", views.politics, name="politics"),
    path("politics/get", views.politics_get, name="politics_get"),
    path("weather/", views.weather, name="weather"),
    path("weather/get", views.weather_get, name="weather_get"),
]

pa/notes/urls.py
from django.urls import path

from . import views

app_name = "notes"

urlpatterns = [
    path("all-notes/", views.all_notes, name="all_notes"),
    path("add-note/", views.add_note, name="add_note"),
    path("note/<int:id>/", views.note, name="note"),
    path("note/<int:id>/edit/", views.edit_note, name="edit_note"),
    path("note/<int:id>/delete/", views.delete_note, name="delete_note"),
    path("find-notes/", views.find_notes, name="find_notes"),
    path("by-name/", views.by_name, name="by_name"),
    path("by-tag/", views.by_tag, name="by_tag"),
    path("all-notes/tag/<str:name>", views.by_tag_name, name="by_tag_name")
]

pa/pa/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views

from .api import NewsQuoteResource

news_quote_resource = NewsQuoteResource()

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.main_page, name="main_page"),
    path("", include("notes.urls")),
    path("", include("contacts.urls")),
    path("users/", include("users.urls")),
    path("news/", include("news.urls")),
    path("storage/", include("storage.urls")),
    path("random_quote_api/", views.random_quote_api, name="random_quote_api"),
    path("road_map/", views.road_map, name="road_map"),

    path("reviews/", views.reviews, name="reviews"),

    re_path(r"^api/", include(news_quote_resource.urls)),
]

pa/urls.py
from django.conf.urls import handler404
from pa.views.error_views import handler404  # импортируйте ваш обработчик

handler404 = 'pa.views.error_views.handler404'

pa/users/urls.py
from django.contrib.auth.views import (PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView)
from django.urls import path

from . import views
from .views import (ActivateAccountView, ActivationSuccessView,
                    EmailVerificationSentView, RegisterView)

app_name = "users"

urlpatterns = [
    # path("", views.users_main, name="users_main"),
    path("register/", RegisterView.as_view(), name="register"),
    path("activate/<uidb64>/<token>/", ActivateAccountView.as_view(), name="activate"),
    path(
        "email-verification-sent/",
        EmailVerificationSentView.as_view(),
        name="email_verification_sent",
    ),
    path(
        "activation-success/",
        ActivationSuccessView.as_view(),
        name="activation_success",
    ),
    path("login/", views.login_view, name="login"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logout_view, name="logout"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

pa/users/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default="default_avatar.png", upload_to="profile_images")

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

pa/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ["username", "password"]


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username", "email", "password"]

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.password = make_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

pa/users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.generic import View
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from .forms import RegistrationForm

# from django.utils.translation import gettext_lazy as _


User = get_user_model()


def users_main(request):
    return render(request, "users/users.html")


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("users:profile")
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", {"form": form})


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            # Send confirmation email
            current_site = get_current_site(request)
            mail_subject = "Activate your account"
            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            message = render_to_string(
                "users/acc_active_email.html",
                {
                    "user": user,
                    "domain": current_site.domain,
                    "protocol": "https" if request.is_secure() else "http",
                    "uid": uid,
                    "token": token,
                },
            )
            email = EmailMessage(mail_subject, message, to=[user.email])
            email.send()
            return redirect("users:email_verification_sent")
    else:
        form = RegistrationForm()
    return render(request, "users/register.html", {"form": form})


@login_required
def profile(request):
    return render(request, "users/profile.html")


def logout_view(request):
    logout(request)
    return redirect("users:login")


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect("activation_success")
    else:
        return HttpResponse("Activation link is invalid!")


def email_verification_sent(request):
    return render(request, "users/email_verification_sent.html")


def activation_success(request):
    return render(request, "users/activation_success.html")


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"
    html_email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    success_message = (
        "An email with instructions to reset your password has been sent to %(email)s."
    )
    subject_template_name = "users/password_reset_subject.txt"


class EmailVerificationSentView(TemplateView):
    template_name = "users/email_verification_sent.html"


class ActivationSuccessView(TemplateView):
    template_name = "users/activation_success.html"


class ActivateAccountView(View):
    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, "Your account has been confirmed.")
            return redirect("users:activation_success")
        else:
            messages.warning(
                request,
                "The confirmation link was invalid, possibly because it has already been used.",
            )
            return redirect("users:email_verification_sent")


class RegisterView(FormView):
    template_name = "users/register.html"
    form_class = RegistrationForm
    success_url = reverse_lazy("users:email_verification_sent")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        current_site = self.request.get_host()
        protocol = "https" if self.request.is_secure() else "http"
        mail_subject = "Activate your account"
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))

        html_message = render_to_string(
            "users/acc_active_email.html",
            {
                "user": user,
                "domain": current_site,
                "uid": uid,
                "token": token,
                "protocol": protocol,
            },
        )

        email = EmailMultiAlternatives(
            subject=mail_subject,
            body="",
            from_email=settings.EMAIL_HOST_USER,
            to=[user.email],
        )

        email.attach_alternative(html_message, "text/html")
        email.send()

        return super().form_valid(form)

pa/users/templates/users/acc_active_email.html
{% autoescape off %}
<body>
  <p>Hi {{ user.username }},</p>
  <p>
    Please click the link below to confirm your email address and complete your
    registration:
  </p>
  <p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}">
      {{ protocol }}://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}</a>
  </p>
  <p>If you didn't request a password reset, please ignore this email.</p>
  <p>Thanks,</p>
  <p>The Our Team</p>
  {% endautoescape %}
</body>

pa/users/templates/users/activation_success.html
{% extends 'base.html' %}

{% block title %}Activation Success{% endblock %}

{% block content %}

<section class="_content_block_1">
    <div class="wr">
      <div class="_15cacd0c">
        <div class="_content_left_block">
          <header class="_af4fe10b">
            <h2 class="_060ab2a4">Ok!</h2>
            <p class="_defae18f"></p>
          </header>
        </div>
        <div class="_content_right_block">
          <div class="_3f613442">
            <h4 class="_8239ae20">Activation Success</h4>
            <div class="_1b1643a8">
              <p>Your account has been successfully activated!</p>
              <p>You can now log into your account</p>
                <div class="um-nav-buttons">
                  <a href="{% url 'users:login' %}" class="_ad787885 btn">
                    <span>Sign In</span></a>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  {% endblock %}

pa/users/templates/users/email_verification_sent.html
{% extends 'base.html' %}

{% block title %}Please confirm your email{% endblock %}

{% block content %}

<section class="_content_block_1">
  <div class="wr">
    <div class="_15cacd0c">
      <div class="_content_left_block">
        <header class="_af4fe10b">
          <h2 class="_060ab2a4">Ok!</h2>
          <p class="_defae18f">You are one step away from completing registration</p>
        </header>
      </div>
      <div class="_content_right_block">
        <div class="_3f613442">
          <h4 class="_8239ae20">Please confirm your email</h4>
          <div class="_1b1643a8">
          <p>The confirm message has been sent to your email.</p>
          <p>Please click on the link to complete registration.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

pa/users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Sign In{% endblock %}

{% block content %}

<section class="_content_block_1">
  <div class="wr">
    <div class="_15cacd0c">
      <div class="_content_left_block">
        <header class="_af4fe10b">
          <h2 class="_060ab2a4">Sign in</h2>
          <p class="_defae18f">
            Welcome
          </p>
        </header>
      </div>
      <div class="_content_right_block">
        <div class="_3f613442">
          <h4 class="_8239ae20">Enter your username and password used during registration</h4>
          <div class="_1b1643a8">
            <form action="{% url 'users:login' %}" method="post">
              {% csrf_token %}
              <div>
                <label> Username: {{ form.username }}</label>
              </div>
            
              <div>
                <label>Password: {{ form.password }} </label>
              </div>
            
              <div class="grid">
                <button type="submit">Submit</button>
                <button type="reset" class="secondary">Reset</button>
              </div>
              <div class="small text-center">
                <a href="{% url 'users:password_reset' %}" class="text-center"
                  ><i>Forgot Password?</i></a
                >
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

pa/users/templates/users/password_reset.html
{% extends 'base.html' %}

{% block title %}Password reset{% endblock %}

{% block content %}

<section class="_content_block_1">
  <div class="wr">
    <div class="_15cacd0c">
      <div class="_content_left_block">
        <header class="_af4fe10b">
          <h2 class="_060ab2a4">Password reset</h2>
          <p class="_defae18f">
            Please enter the email you used during registration
          </p>
        </header>
      </div>
      <div class="_content_right_block">
        <div class="_3f613442">
          <h4 class="_8239ae20">An email with further instructions will be sent to the specified email address.</h4>
          <div class="_1b1643a8">
            <form method="post">
              {% csrf_token %} {{ form.as_p }}
              <button type="submit">Request password reset</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

pa/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Password reset request sent{% endblock %}

{% block content %}

<section class="_content_block_1">
    <div class="wr">
      <div class="_15cacd0c">
        <div class="_content_left_block">
          <header class="_af4fe10b">
            <h2 class="_060ab2a4">Ok!</h2>
            <p class="_defae18f"></p>
          </header>
        </div>
        <div class="_content_right_block">
          <div class="_3f613442">
            <h4 class="_8239ae20">Password reset complete!</h4>
            <div class="_1b1643a8">
                You can now log in to the site with a new password
                <div class="um-nav-buttons">
                  <a href="{% url 'users:login' %}" class="_ad787885 btn">
                    <span>Sign In</span></a>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  {% endblock %}

pa/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}New password{% endblock %}

{% block content %}

<section class="_content_block_1">
  <div class="wr">
    <div class="_15cacd0c">
      <div class="_content_left_block">
        <header class="_af4fe10b">
          <h2 class="_060ab2a4">New password</h2>
          <p class="_defae18f"></p>
        </header>
      </div>
      <div class="_content_right_block">
        <div class="_3f613442">
          <h4 class="_8239ae20">Please, enter a new password</h4>
          <div class="_1b1643a8">
            <form method="post">
              {% csrf_token %} {{ form.as_p }}
              <button type="submit">Save new password</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

pa/users/templates/users/password_reset_done.html
{% extends 'base.html' %} 

{% block title %}Password reset request sent{% endblock %}

{% block content %}

<section class="_content_block_1">
    <div class="wr">
      <div class="_15cacd0c">
        <div class="_content_left_block">
          <header class="_af4fe10b">
            <h2 class="_060ab2a4">Ok!</h2>
            <p class="_defae18f"></p>
          </header>
        </div>
        <div class="_content_right_block">
          <div class="_3f613442">
            <h4 class="_8239ae20">Password reset request sent</h4>
            <div class="_1b1643a8">
                We've emailed you with instructions on how to reset your password.
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  {% endblock %}

pa/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
  <p>Hi {{ user.username }},</p>
  <p>
    You requested a password reset for your account. Please follow this link to
    set a new password:
  </p>
  <p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
      {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}</a>
  </p>
  <p>If you didn't request a password reset, please ignore this email.</p>
  <p>Thanks,</p>
  <p>The Our Team</p>
  {% endautoescape %}
</body>

pa/users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}

<section class="_content_block_1">
    <div class="wr">
      <div class="_15cacd0c">
        <div class="_content_left_block">
          <header class="_af4fe10b">
            <h2 class="_060ab2a4">Profile</h2>
            <p class="_defae18f">
                Page under construction
            </p>
          </header>
        </div>
        <div class="_content_right_block">
          <div class="_3f613442">
            <h4 class="_8239ae20">Welcome, {{ user.username }}!</h4>
            <div class="_1b1643a8">
                <p>This page will contain account statistics and some settings in the future.</p>
                <p>But now you can take advantage of all the functions of the site</p>
                <ul class="um-nav-links">
                    <li><a href="{% url 'news:main' %}">News</a></li>
                    <li><a href="{% url 'contacts:contacts' %}">Contacts</a></li>
                    <li><a href="{% url 'notes:all_notes' %}">Notes</a></li>
                    <li><a href="{% url 'storage:file_list' %}">File storage</a></li>
                    <li><a href="{% url 'users:profile' %}">Profile</a></li>
                    <li><a href="{% url 'users:logout' %}">Logout</a></li>
                </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  {% endblock %}

pa/users/templates/users/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}

<section class="_content_block_1">
  <div class="wr">
    <div class="_15cacd0c">
      <div class="_content_left_block">
        <header class="_af4fe10b">
          <h2 class="_060ab2a4">Register</h2>
          <p class="_defae18f">
            In a few moments you will be able to use all the features of the site
          </p>
        </header>
      </div>
      <div class="_content_right_block">
        <div class="_3f613442">
          <h4 class="_8239ae20">Please fill in the form below</h4>
          <div class="_1b1643a8">
            <form method="post" action="{% url 'users:register' %}">
              {% csrf_token %}
              <div>
                <label> Username: {{ form.username }} </label>
                <span>{{ form.errors.username }}</span>
              </div>
              <div>
                <label> Email: {{ form.email }} </label>
                <span>{{ form.errors.email }}</span>
              </div>
              <div>
                <label> Password: {{ form.password }} </label>
                <span>{{ form.errors.password }}</span>
              </div>
              <div>
                <label> Password confirmation: {{ form.confirm_password }} </label>
                <span>{{ form.errors.confirm_password }}</span>
              </div>
              <div class="grid">
                <button type="submit">Submit</button>
                <button type="reset" class="secondary">Reset</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

pa/users/templates/users/users.html
{% extends 'base.html' %} {% block title %}Register{% endblock %}
{% block content %}
<h2>Users</h2>
{% endblock %}