pa/contacts/urls.py
from django.urls import path

from . import views

app_name = "contacts"

urlpatterns = [
    path("contacts/", views.contacts, name="contacts"),
    path("contact/<int:id>/", views.contact, name="contact"),
    path("contact/<int:id>/delete/", views.delete_contact, name="delete_contact"),
    path("contact/<int:id>/edit", views.edit_contact, name="edit_contact"),
    path("contacts/create/", views.create_contact, name="create_contact"),
    path("contacts/search/", views.find_contact, name="find_contact"),
    path("contacts/upcoming_birthdays/", views.upcoming_birthdays, name="upcoming_birthdays"),
]

pa/pa/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views

from .api import NewsQuoteResource

news_quote_resource = NewsQuoteResource()

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.main_page, name="main_page"),
    path("", include("notes.urls")),
    path("", include("contacts.urls")),
    path("users/", include("users.urls")),
    path("news/", include("news.urls")),
    path("storage/", include("storage.urls")),
    path("random_quote_api/", views.random_quote_api, name="random_quote_api"),
    path("road_map/", views.road_map, name="road_map"),

    path("reviews/", views.reviews, name="reviews"),

    re_path(r"^api/", include(news_quote_resource.urls)),
]

pa/urls.py
from django.conf.urls import handler404
from pa.views.error_views import handler404  # импортируйте ваш обработчик

handler404 = 'pa.views.error_views.handler404'

pa/contacts/models.py
from django.contrib.auth.models import User
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=30, null=False)
    address = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=15, null=True)
    email = models.CharField(max_length=50, null=True)
    birthday = models.DateField(null=True, blank=True)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return (f"{self.name}, {self.address},"
                f"{self.phone}, {self.email},"
                f"{self.birthday}")

pa/contacts/forms.py
from django import forms

from .models import Contact
from .validators import EmailValidator, NameValidator, PhoneValidator, BirthdayValidator


class ContactForm(forms.ModelForm):
    name = forms.CharField(
        max_length=30,
        required=True,
        validators=[NameValidator()]
    )
    address = forms.CharField(
        max_length=100,
        required=False
    )
    phone = forms.CharField(
        max_length=15,
        required=False,
        validators=[PhoneValidator()]
    )
    email = forms.CharField(
        max_length=50,
        required=False,
        validators=[EmailValidator()]
    )
    birthday = forms.DateField(
        required=False,
        validators=[BirthdayValidator()],
        widget=forms.DateInput(attrs={'type': 'date'})
    )

    class Meta:
        model = Contact
        fields = ["name", "address", "phone", "email", "birthday"]
        exclude = ["added_by"]

pa/contacts/views.py
from datetime import date, timedelta
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q

from .models import Contact
from .forms import ContactForm


def paginator(request, data):
    paginator = Paginator(data, 5)  # Number elements on page
    page = request.GET.get('page', 1)
    try:
        data_paginated = paginator.page(page)
    except PageNotAnInteger:
        data_paginated = paginator.page(1)
    except EmptyPage:
        data_paginated = paginator.page(paginator.num_pages)
    return data_paginated


@login_required
def contact(request, id):
    contact = get_object_or_404(Contact, id=id, added_by=request.user)
    return render(request, "contacts/contact.html", {"contact": contact})


@login_required
def contacts(request):
    contacts = Contact.objects.filter(added_by=request.user).all().order_by('name')
    return render(
        request,
        "contacts/contacts.html",
        {
            "contacts": paginator(request, contacts)
        }
    )


@login_required
def create_contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save()
            contact.added_by = request.user
            contact.save()
            return redirect("contacts:contact", contact.id)
        else:
            return render(request, "contacts/create_contact.html", {"form": form})
    return render(request, "contacts/create_contact.html", {"form": ContactForm()})


@login_required
def edit_contact(request, id):
    contact = get_object_or_404(Contact, id=id, added_by=request.user)
    if request.method == "POST":
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            form.save()
            return redirect("contacts:contact", id)
    else:
        form = ContactForm(instance=contact)

    return render(request, "contacts/edit_contact.html", {"form": form, "contact": contact})


@login_required
def delete_contact(request, id):
    contact = get_object_or_404(Contact, id=id, added_by=request.user)
    if request.method == "POST":
        contact.delete()
        return redirect("contacts:contacts")
    return render(request, "contacts/delete_contact.html", {"contact": contact})


@login_required
def find_contact(request):
    result = []
    if request.method == "POST":
        search_word = request.POST.get("search_word", "")
        result = Contact.objects.filter(name__icontains=search_word, added_by=request.user).order_by('name')
        if not result.exists():
            result = Contact.objects.filter(email__icontains=search_word, added_by=request.user).order_by('name')
        if not result.exists():
            result = Contact.objects.filter(phone__icontains=search_word, added_by=request.user).order_by('name')
    return render(
        request,
        "contacts/search_result.html",
        {
            "contacts": paginator(request, result)
        }
    )


@login_required
def upcoming_birthdays(request):
    today = date.today()
    end_date = today + timedelta(days=7)

    upcoming_birthdays = Contact.objects.filter(
        added_by=request.user,
        birthday__isnull=False,
        birthday__month__in=[today.month, end_date.month],
        birthday__day__gte=today.day if today.month == end_date.month else 1,
        birthday__day__lte=end_date.day if today.month == end_date.month else 31
    ).order_by('-birthday')
    return render(
        request,
        "contacts/contacts.html",
        {
            "contacts": paginator(request, upcoming_birthdays)
        }
    )

pa/contacts/templates/contacts/_contact_detail.html
<a href="/contact/{{ contact.id }}"><strong>{{ contact.name }}</strong></a>
<ul class="information">
    {% if contact.phone %}
        <li>Phone: {{ contact.phone }}</li>
    {% endif %}
    {% if contact.email %}
        <li>Email: {{ contact.email }}</li>
    {% endif %}
    {% if contact.address %}
        <li>Address: {{ contact.address }}</li>
    {% endif %}
    {% if contact.birthday %}
        <li>Birthday: {{ contact.birthday }}</li>
    {% endif %}
</ul>

pa/contacts/templates/contacts/_contact_menu.html
<a href="/contact/{{contact.id}}/edit">Edit</a>
<a href="/contact/{{contact.id}}/delete">Delete</a>

pa/contacts/templates/contacts/_contacts_menu.html
<ul>
    <li><a href="{% url 'contacts:contacts' %}">Contacts</a></li>
    <li><a href="{% url 'contacts:create_contact' %}">New contact</a></li>
    <li><a href="{% url 'contacts:upcoming_birthdays' %}">Upcoming Birthdays</a></li>
</ul>

pa/contacts/templates/contacts/_search_form.html
<form class="search-form"
      action="{% url 'contacts:find_contact' %}"
      method="post">
    {% csrf_token %}
    <input type="text"
           class="form-control"
           id="id_search_word"
           name="search_word">
    <input type="submit"
           value="Search"
           class="btn btn-light btn-sm border border-1 ms-1">
</form>

pa/contacts/templates/contacts/contact.html
{% extends 'base.html' %}

{% block title %}Full info contact - {{ contact.name }}{% endblock %}

{% block content%}

<section class="_content_block_1">
    <div class="wr">
      <div class="_15cacd0c">
        <div class="_content_left_block">
          <header class="_af4fe10b">
            <h2 class="_060ab2a4">Contacts</h2>
            {% include 'contacts/_contacts_menu.html' %}
            {% include 'contacts/_search_form.html' %}
          </header>
        </div>
        <div class="_content_right_block">
          <div class="_3f613442">
            <h4 class="_8239ae20">Details of contact "{{ contact.name }}"</h4>
            <br />
            <div class="_1b1643a8">
                <div>
                    {% include 'contacts/_contact_detail.html' %}
                    {% include 'contacts/_contact_menu.html' %}

                    <br /><br />
                    <li><a href="{% url 'contacts:contacts' %}">Go to all contacts</a></li>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  {% endblock %}

pa/contacts/templates/contacts/contacts.html
{% extends 'base.html' %}

{% block title %}Contacts{% endblock %}

{% block content%}

<section class="_content_block_1">
    <div class="wr">
      <div class="_15cacd0c">
        <div class="_content_left_block">
          <header class="_af4fe10b">
            <h2 class="_060ab2a4">Contacts</h2>
            {% include 'contacts/_contacts_menu.html' %}
            {% include 'contacts/_search_form.html' %}
          </header>
        </div>
        <div class="_content_right_block">
          <div class="_3f613442">
            <h4 class="_8239ae20">List of contacts</h4>
            <br />
            <div class="_1b1643a8">
                <ul>
                    {% for contact in contacts %}
                      {% include 'contacts/_contact_detail.html' %}
                      {% include 'contacts/_contact_menu.html' %}
                      <br /> <br />
                    {% endfor %}
                </ul>
                {% include 'contacts/pagination.html' %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  {% endblock %}

pa/contacts/templates/contacts/create_contact.html
{% extends 'base.html' %}

{% block title %}Add new contact{% endblock %}

{% block content%}

<section class="_content_block_1">
    <div class="wr">
      <div class="_15cacd0c">
        <div class="_content_left_block">
          <header class="_af4fe10b">
            <h2 class="_060ab2a4">Contacts</h2>
            {% include 'contacts/_contacts_menu.html' %}
          </header>
        </div>
        <div class="_content_right_block">
          <div class="_3f613442">
            <h4 class="_8239ae20">Add new contact</h4>
            <br />
            <div class="_1b1643a8">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Save Contact</button>
                </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  {% endblock %}

pa/contacts/templates/contacts/delete_contact.html
{% extends 'base.html' %}

{% block title %}Delete contact {{ contact.name }}{% endblock %}

{% block content%}

<section class="_content_block_1">
    <div class="wr">
      <div class="_15cacd0c">
        <div class="_content_left_block">
          <header class="_af4fe10b">
            <h2 class="_060ab2a4">Contacts</h2>
            {% include 'contacts/_contacts_menu.html' %}
            {% include 'contacts/_search_form.html' %}
          </header>
        </div>
        <div class="_content_right_block">
          <div class="_3f613442">
            <h4 class="_8239ae20">Delete contact</h4>
            <br />
            <div class="_1b1643a8">
                <p>Are you sure you want to delete the contact?</p>
                {% include 'contacts/_contact_detail.html' %}
                <form method="post">
                  {% csrf_token %}
                  <button type="submit">Yes, delete</button>
                  <a href="{% url 'contacts:contacts' %}">Cancel</a> or <a href="/contact/{{contact.id}}/edit">Edit</a>
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  {% endblock %}

pa/contacts/templates/contacts/edit_contact.html
{% extends "base.html" %}

{% block title %}Edit contact "{{ contact.name }}"{% endblock %}

{% block content %}

<section class="_content_block_1">
    <div class="wr">
      <div class="_15cacd0c">
        <div class="_content_left_block">
          <header class="_af4fe10b">
            <h2 class="_060ab2a4">Contacts</h2>
            {% include 'contacts/_contacts_menu.html' %}
            {% include 'contacts/_search_form.html' %}
          </header>
        </div>
        <div class="_content_right_block">
          <div class="_3f613442">
            <h4 class="_8239ae20">Edit contact</h4>
            <br />
            <div class="_1b1643a8">
                <form method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit">Save Contact</button>
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  {% endblock %}

pa/contacts/templates/contacts/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if contacts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ files.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">
            Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
        </span>

        {% if contacts.has_next %}
            <a href="?page={{ contacts.next_page_number }}">next</a>
            <a href="?page={{ contacts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

pa/contacts/templates/contacts/search_result.html
{% extends 'base.html' %}

{% block title %}Search result{% endblock %}

{% block content%}

<section class="_content_block_1">
    <div class="wr">
      <div class="_15cacd0c">
        <div class="_content_left_block">
          <header class="_af4fe10b">
            <h2 class="_060ab2a4">Contacts</h2>
            {% include 'contacts/_contacts_menu.html' %}
            {% include 'contacts/_search_form.html' %}
          </header>
        </div>
        <div class="_content_right_block">
          <div class="_3f613442">
            <h4 class="_8239ae20">Search result:</h4>
            <br />
            <div class="_1b1643a8">
                <ul>
                    {% for contact in contacts %}
                      {% include 'contacts/_contact_detail.html' %}
                      {% include 'contacts/_contact_menu.html' %}
                      <br /> <br />
                    {% endfor %}
                </ul>
                {% include 'contacts/pagination.html' %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
{% endblock %}